### ISSUE TITLE
Add missing checksums

### ISSUE THREAD

**Issue by sambernet** [brutaldev/chocolatey-packages#6]
The current chocolatey version does not (by default) support checksums. This leads to the install of 'screenpresso' failing without adding the `--allowEmptyCheckums` flag:

```
ERROR: Empty checksums are no longer allowed by default for non-secure sources. Please ask the maintainer to add checksu
ms to this package. In the meantime if you need this package to work correctly, please enable the feature allowEmptyChec
ksums or provide the runtime switch '--allowEmptyChecksums'. We strongly advise against allowing empty checksums for HTT
P/FTP sources.
```

Packages with no checksums are also ruled out at my company for security reasons.

**Comment by sambernet** [comment]
Was under the impression this is the git repo for 'screenpresso' chocolatey package. Noticed this is not the case, so closing this issue. Sorry for the commotion.

**Comment by brutaldev** [comment]
Hi @sambernet, this is the repo for the package. I'll upload the new version (1.6.4) with checksums.

**Comment by sambernet** [comment]
Sorry didn't take my time for this :-)

Read the chocolatey instructions only after filing the issue, then used the "contact maintainers" as instructed and closed the issue. Glad the issue is still valid.

Thanks a lot for your efforts, appreciated.

**Comment by brutaldev** [comment]
New package is pushed and awaiting moderation: https://chocolatey.org/packages/screenpresso/1.6.4
